#!/usr/bin/env bash
# This script is displaying "Best School" 10 time

x=10
while [ $x -ne 0 ]; do
  if [ $x -eq 9 ]; then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  ((x--))
done
